//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetail
    {
        public int ID { get; set; }
        public int IDDevice { get; set; }
        public int IDDelivery { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateExpires { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string Note { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Device Device { get; set; }
    }
}
